/**
 * Nuxt resolves `~`/`@`/`~~`/`@@` through its own build step
 * (`.nuxt/tsconfig*.json`, generated by `nuxt prepare`), which does not exist
 * in a shallow clone — see the failure mode documented at
 * `adapters/depgraph/index.ts`. dependency-cruiser cannot run that build, so
 * this recreates only the alias roots it needs, from Nuxt's own documented
 * defaults, without executing the repo's config.
 *
 * Nuxt 4 moved the app source root from `<root>` to `<root>/app` by default;
 * Nuxt 3 kept it at `<root>`. An explicit `srcDir` in `nuxt.config.*` always
 * wins over either default, so it is read first (heuristically, matching this
 * module's other config extractors — never executed).
 */
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const NUXT_CONFIG_NAMES = ['nuxt.config.ts', 'nuxt.config.js', 'nuxt.config.mjs'] as const;

const SRC_DIR_PATTERN = /srcDir\s*:\s*['"`]([^'"`]+)['"`]/;

export function detectAliases(root: string): Record<string, string> | null {
  const configPath = findNuxtConfig(root);
  if (!configPath) return null;

  const srcDir = resolveSrcDir(root, configPath);
  return {
    '~': srcDir,
    '@': srcDir,
    '~~': root,
    '@@': root,
  };
}

function findNuxtConfig(root: string): string | null {
  for (const name of NUXT_CONFIG_NAMES) {
    const p = join(root, name);
    if (existsSync(p)) return p;
  }
  return null;
}

function resolveSrcDir(root: string, configPath: string): string {
  const explicit = readExplicitSrcDir(configPath);
  if (explicit) return join(root, explicit);
  return existsSync(join(root, 'app')) ? join(root, 'app') : root;
}

function readExplicitSrcDir(configPath: string): string | null {
  try {
    const match = readFileSync(configPath, 'utf8').match(SRC_DIR_PATTERN);
    return match ? match[1]! : null;
  } catch {
    return null;
  }
}
