import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", marginBottom: 14 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: {
    marginLeft: "auto",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  scopeNote: {
    fontSize: 12,
    color: "var(--text-secondary)",
    margin: "-6px 0 12px",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  saveError: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 7,
    padding: "10px 12px",
    marginBottom: 14,
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--crit)",
  } satisfies CSSProperties,
  filterWrap: { marginBottom: 10 } satisfies CSSProperties,
  orderHint: {
    fontSize: 12,
    color: "var(--text-muted)",
    margin: "10px 0 18px",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  skeletonStack: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  divider: { height: 1, background: "var(--border)", margin: "14px 0" } satisfies CSSProperties,
  row: (attached: boolean, dragging?: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 12px",
    borderRadius: 7,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: attached ? "var(--border-strong)" : "var(--border)",
    borderStyle: attached ? "solid" : "dashed",
    background: attached ? "var(--bg-elevated)" : "transparent",
    opacity: dragging ? 0.5 : 1,
  }),
  dragHandle: { color: "var(--text-muted)", cursor: "grab", flexShrink: 0 } satisfies CSSProperties,
  dragHandleSpacer: { width: 14, flexShrink: 0 } satisfies CSSProperties,
  moveButtons: { display: "flex", flexShrink: 0 } satisfies CSSProperties,
  moveButtonsSpacer: { width: 48, flexShrink: 0 } satisfies CSSProperties,
  rowMain: { minWidth: 0, display: "flex", alignItems: "baseline", gap: 8 } satisfies CSSProperties,
  rowFolder: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
  } satisfies CSSProperties,
  badges: {
    display: "flex",
    gap: 6,
    marginLeft: "auto",
    flexShrink: 0,
    alignItems: "center",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 18,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  limit: { marginLeft: "auto", fontSize: 12, color: "var(--warn)" } satisfies CSSProperties,
} as const;
