import type { CSSProperties } from "react";

export const s = {
  footer: { display: "flex", gap: 10, justifyContent: "flex-end" } satisfies CSSProperties,
  body: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  picker: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  pickLabel: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "32px 16px",
    borderRadius: 8,
    border: "1px dashed var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  } satisfies CSSProperties,
  fileInput: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0,0,0,0)",
    whiteSpace: "nowrap",
    border: 0,
  } satisfies CSSProperties,
  preview: { display: "flex", flexDirection: "column" } satisfies CSSProperties,
  skipped: {
    fontSize: 12,
    color: "var(--text-muted)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "8px 12px",
    marginBottom: 20,
  } satisfies CSSProperties,
  markdown: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 16,
    background: "var(--bg-elevated)",
    fontSize: 13,
  } satisfies CSSProperties,
} as const;
