import type { CSSProperties } from "react";

export const s = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  textInput: {
    fontSize: 13,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  diffTextarea: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    lineHeight: 1.5,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    minHeight: 120,
    resize: "vertical",
  } satisfies CSSProperties,
  expectedOutputHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  } satisfies CSSProperties,
  expectedOutputTextarea: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    lineHeight: 1.5,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    minHeight: 140,
    resize: "vertical",
  } satisfies CSSProperties,
  badgeValid: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--ok, var(--text-secondary))",
    background: "var(--ok-bg, var(--bg-hover))",
    borderRadius: 4,
    padding: "1px 8px",
  } satisfies CSSProperties,
  badgeInvalid: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 4,
    padding: "1px 8px",
  } satisfies CSSProperties,
  insertButton: {
    alignSelf: "flex-start",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "5px 10px",
    cursor: "pointer",
  } satisfies CSSProperties,
  kindChoiceRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  kindChoiceLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  kindChoiceButton: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent)",
    background: "var(--accent-bg)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "4px 10px",
    cursor: "pointer",
  } satisfies CSSProperties,
  saveButton: {
    alignSelf: "flex-start",
    fontSize: 13,
    fontWeight: 600,
    color: "#fff",
    background: "var(--accent)",
    border: "1px solid var(--accent)",
    borderRadius: 6,
    padding: "7px 16px",
    cursor: "pointer",
  } satisfies CSSProperties,
} as const;
