import type { CSSProperties } from "react";

export const s = {
  wrap: { padding: "28px 32px 48px", maxWidth: 1200 } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 20,
  } satisfies CSSProperties,
  headerMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  h1: { fontSize: 26, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  subtitle: { marginTop: 6, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  badges: { display: "flex", gap: 8, marginTop: 10 } satisfies CSSProperties,
  metaRow: { display: "flex", gap: 16, marginTop: 10 } satisfies CSSProperties,
  meta: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  } satisfies CSSProperties,
  failureBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 8,
    padding: "14px 16px",
    marginBottom: 20,
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  failureTitle: { fontSize: 14, fontWeight: 600, color: "var(--crit)" } satisfies CSSProperties,
  failureReason: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  failureCost: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  body: { display: "flex", gap: 28, alignItems: "flex-start" } satisfies CSSProperties,
  sections: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  } satisfies CSSProperties,
  sectionAnchor: { scrollMarginTop: 16 } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  runningNote: { marginTop: 4, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
