import type { SmartDiffRole } from '@devdigest/shared';

export const ROLE_ORDER: readonly SmartDiffRole[] = ['core', 'wiring', 'boilerplate'] as const;

export const BOILERPLATE_FILENAMES = [
  'package-lock.json',
  'npm-shrinkwrap.json',
  'pnpm-lock.yaml',
  'pnpm-workspace.yaml',
  'yarn.lock',
  'bun.lock',
  'bun.lockb',
  'deno.lock',
  'composer.lock',
  'gemfile.lock',
  'poetry.lock',
  'pipfile.lock',
  'uv.lock',
  'pdm.lock',
  'pixi.lock',
  'cargo.lock',
  'cargo.toml.orig',
  'go.sum',
  'gopkg.lock',
  'glide.lock',
  'packages.lock.json',
  'gradle.lockfile',
  'flake.lock',
  'module.bazel.lock',
  '.terraform.lock.hcl',
  'package.resolved',
  '.secrets.baseline',
] as const;

export const BOILERPLATE_SEGMENTS = [
  'node_modules',
  'bower_components',
  'dist',
  'build',
  'out',
  'coverage',
  'htmlcov',
  '.next',
  '.turbo',
  '.cache',
  '__snapshots__',
  '__generated__',
  '__fixtures__',
  'generated',
  'vendor',
  'third_party',
  'testdata',
  'assets',
  'public',
  '.venv',
  'target',
  'obj',
  'pods',
  '.idea',
] as const;

export const BOILERPLATE_SUFFIXES = [
  '.lock',
  '.snap',
  '.map',
  '.min.js',
  '.min.mjs',
  '.min.css',
  '.generated.ts',
  '.generated.js',
  '.gen.ts',
  '.gen.go',
  '.pb.go',
  '_pb.ts',
  '_pb2.py',
  '.d.ts',
  '.designer.cs',
  '.designer.vb',
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.avif',
  '.ico',
  '.svg',
  '.woff',
  '.woff2',
  '.ttf',
  '.otf',
  '.eot',
  '.pdf',
  '.zip',
  '.gz',
  '.tgz',
  '.tar',
  '.7z',
  '.rar',
  '.mp3',
  '.mp4',
  '.wav',
  '.webm',
  '.bmp',
  '.tiff',
  '.wasm',
  '.pyc',
  '.class',
  '.jar',
  '.war',
  '.so',
  '.dylib',
  '.dll',
  '.exe',
  '.bin',
  '.db',
  '.sqlite',
] as const;

export const WIRING_FILENAMES = [
  'package.json',
  'tsconfig.json',
  'tsconfig.build.json',
  'jsconfig.json',
  'dockerfile',
  'docker-compose.yml',
  'docker-compose.yaml',
  '.dockerignore',
  'makefile',
  'procfile',
  '.gitignore',
  '.gitattributes',
  '.npmrc',
  '.nvmrc',
  '.editorconfig',
  'renovate.json',
  'turbo.json',
  'drizzle.config.ts',
  'next.config.js',
  'next.config.mjs',
  'next.config.ts',
  'postcss.config.mjs',
  'vitest.config.ts',
  'vitest.setup.ts',
  'playwright.config.ts',
  'gradlew',
  'gradlew.bat',
  'mvnw',
  'mvnw.cmd',
  'index.ts',
  'index.tsx',
  'index.js',
  'index.jsx',
  'index.mjs',
  'mod.ts',
  'barrel.ts',
] as const;

export const WIRING_SEGMENTS = [
  '.github',
  'workflows',
  '.circleci',
  '.gitlab',
  'ci',
  'migrations',
  'migration',
  'seeds',
  'scripts',
  'infra',
  'infrastructure',
  'deploy',
  'deployment',
  'k8s',
  'kubernetes',
  'helm',
  'terraform',
  '.husky',
  '.vscode',
  '.claude',
  'docs',
  'specs',
  'plans',
  'messages',
] as const;

export const WIRING_SUFFIXES = [
  '.config.ts',
  '.config.js',
  '.config.mjs',
  '.config.cjs',
  '.config.json',
  '.config.yml',
  '.config.yaml',
  '.env',
  '.env.example',
  '.env.local',
  '.env.production',
  '.yml',
  '.yaml',
  '.toml',
  '.ini',
  '.cfg',
  '.sql',
  '.md',
  '.mdx',
] as const;

export const TEST_SEGMENTS = [
  '__tests__',
  '__mocks__',
  'test',
  'tests',
  'e2e',
  'spec',
] as const;

export const TEST_SUFFIXES = [
  '.test.ts',
  '.test.tsx',
  '.test.js',
  '.test.jsx',
  '.it.test.ts',
  '.spec.ts',
  '.spec.tsx',
  '.spec.js',
  '.spec.jsx',
] as const;

export const KNOWN_SEVERITIES = ['CRITICAL', 'WARNING', 'SUGGESTION'] as const;

export const SEVERITY_WEIGHT: Readonly<Record<string, number>> = {
  CRITICAL: 10_000,
  WARNING: 100,
  SUGGESTION: 1,
};

export const TOO_BIG_REVIEWABLE_LINES = 400;
export const TOO_BIG_CORE_FILES = 12;
export const SPLIT_KEY_SEGMENTS = 2;
export const SPLIT_ROOT_KEY = '(root)';
export const MIN_FILES_PER_SPLIT = 2;
export const MIN_SPLITS_TO_SUGGEST = 2;
export const MAX_PROPOSED_SPLITS = 4;
export const MAX_FINDING_LINE_SPAN = 500;
export const MAX_LOGGED_ORPHAN_SAMPLES = 5;
