import type { CSSProperties } from "react";

export const s = {
  // No flex gap here: FormField already carries marginBottom, and stacking the
  // two produced 36px between fields against the design's 20px.
  body: { padding: 24 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 20,
    padding: "12px 14px",
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--accent)",
    background: "var(--accent-bg)",
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  bannerIcon: { color: "var(--accent)", flexShrink: 0, marginTop: 2 } satisfies CSSProperties,
  bannerText: { minWidth: 0 } satisfies CSSProperties,
  errorBanner: {
    marginBottom: 20,
    padding: "10px 12px",
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 13,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  row: { display: "flex", gap: 20, alignItems: "flex-start" } satisfies CSSProperties,
  rowItem: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  toggleLocked: {
    opacity: 0.5,
    pointerEvents: "none",
    display: "inline-flex",
  } satisfies CSSProperties,
  diffToggle: { alignSelf: "flex-start" } satisfies CSSProperties,
  diff: {
    margin: 0,
    marginTop: 8,
    padding: "10px 12px",
    maxHeight: 220,
    overflow: "auto",
    borderRadius: 7,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: "18px",
    whiteSpace: "pre",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
  } satisfies CSSProperties,
  footerNote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  footerActions: { marginLeft: "auto", display: "flex", gap: 10 } satisfies CSSProperties,
  loading: { fontSize: 13, color: "var(--text-muted)", padding: "24px 0" } satisfies CSSProperties,
} as const;
